<a href="https://colab.research.google.com/github/niloofar20/second-KNN/blob/main/Copy_of_Untitled10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn import preprocessing

In [33]:
df = pd.read_csv('/content/drug200.csv')
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [34]:
X = df[['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']].values
X[0:5]
Y = df['Drug']
Y[0:5]

0    drugY
1    drugC
2    drugC
3    drugX
4    drugY
Name: Drug, dtype: object

In [35]:
from sklearn.preprocessing import LabelEncoder
le_sex = LabelEncoder()
le_BP = LabelEncoder()
le_Chol = LabelEncoder()
le_sex.fit(['F','M'])
X[:,1] = le_sex.transform(X[:,1])
le_BP.fit([ 'LOW', 'NORMAL', 'HIGH'])
X[:,2] = le_BP.transform(X[:,2])
le_Chol.fit([ 'NORMAL', 'HIGH'])
X[:,3] = le_Chol.transform(X[:,3])
X[0:5]
scalar = preprocessing.StandardScaler()
scalar.fit(X)
X_std = scalar.transform(X)
X_std[0:5]

array([[-1.29159102, -1.040833  , -1.11016894, -0.97043679,  1.28652212],
       [ 0.16269866,  0.96076892,  0.10979693, -0.97043679, -0.4151454 ],
       [ 0.16269866,  0.96076892,  0.10979693, -0.97043679, -0.82855818],
       [-0.988614  , -1.040833  ,  1.32976279, -0.97043679, -1.14996267],
       [ 1.0110343 , -1.040833  ,  0.10979693, -0.97043679,  0.27179427]])

In [36]:
le_Y = LabelEncoder()
le_Y.fit(['drugA', 'drugB', 'drugC', 'drugX', 'drugY'])
Y = le_Y.transform(Y)
Y[0:5]

array([4, 2, 2, 3, 4])

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_std, Y, test_size=0.2, random_state=3)

In [38]:
x_train_scale = scalar.fit_transform(X_train)
x_test_scale = scalar.transform(X_test)

In [39]:
from sklearn.tree import DecisionTreeClassifier
my_modle = DecisionTreeClassifier(random_state=0)
my_modle.fit(x_train_scale, Y_train)
y_predict = my_modle.predict(x_test_scale)

In [40]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, y_predict)

1.0

In [41]:
from sklearn.neighbors import KNeighborsClassifier
my_modle = KNeighborsClassifier(n_neighbors=5)
my_modle.fit(x_train_scale, Y_train)
y_predict = my_modle.predict(x_test_scale)
accuracy_score(Y_test, y_predict)

0.725

In [42]:
  #plot
import plotly.graph_objects as go
from sklearn.datasets import make_moons
A,B = make_moons(noise=0.3, random_state=3)
fig = go.Figure()
fig.add_trace(go.Scatter(x=A[:,0], y=A[:,1], mode='markers', marker=dict(color=B, showscale=False)))
fig.show()